-- Stored Procedures
GO
USE QuanLyQuanCf

--====>>>ĐĂNG NHẬP
--Load form đăng nhập
GO
CREATE PROC SP_DANGNHAP
@taikhoan nvarchar(100), @matkhau nvarchar(100)
AS
BEGIN
	SELECT *
	FROM NHANVIEN
	WHERE MANV = @taikhoan AND MATKHAU = @matkhau
END

--====>>>NHÂN VIÊN
--Load nhân viên
GO
CREATE PROC SP_NHANVIEN_LOAD
AS
BEGIN
	SELECT *
	FROM NHANVIEN
END

--Load Combobox theo tên nhân viên
GO
CREATE PROC SP_NHANVIEN_LOADCOMBOBOX
AS
BEGIN
	SELECT TENNV
	FROM NHANVIEN
	GROUP BY TENNV
END

--Lấy số lớn nhất của mã nhân viên
GO
CREATE PROC SP_GETMANV
AS
BEGIN
	SELECT TOP (1) CAST(RIGHT(MANV, 4) AS INTEGER) + 1 AS MASONV
	FROM NHANVIEN
	ORDER BY MANV DESC
END


--Thêm nhân viên
GO
CREATE PROC SP_NHANVIEN_THEM
	@MANV NVARCHAR(10),
	@TENNV NVARCHAR(100),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(5),
	@DIACHI NVARCHAR(100),
	@DIENTHOAI VARCHAR(11),
	@MATKHAU NVARCHAR(100),
	@QUYEN NVARCHAR(100) ,
	@LUONGCOBAN MONEY
AS
BEGIN
	INSERT INTO NHANVIEN(MANV, TENNV, NGAYSINH, GIOITINH, DIACHI, DIENTHOAI, MATKHAU, QUYEN, LUONGCOBAN)
	VALUES(@MANV, @TENNV, @NGAYSINH, @GIOITINH, @DIACHI, @DIENTHOAI, @MATKHAU, @QUYEN, @LUONGCOBAN)
END


--Xóa nhân viên
GO
CREATE PROC SP_NHANVIEN_XOA
	@MANV NVARCHAR(10)
AS
BEGIN
	DELETE FROM NHANVIEN WHERE @MANV = MANV AND QUYEN != 'Admin' 
END

--Sửa nhân viên
GO
CREATE PROC SP_NHANVIEN_SUA
	@MANV NVARCHAR(10),
	@TENNV NVARCHAR(100),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(5),
	@DIACHI NVARCHAR(100),
	@DIENTHOAI VARCHAR(11),
	@QUYEN NVARCHAR(100) ,
	@LUONGCOBAN MONEY
AS
BEGIN
	UPDATE NHANVIEN SET TENNV = @TENNV, NGAYSINH = @NGAYSINH, GIOITINH = @GIOITINH, DIACHI = @DIACHI, DIENTHOAI = @DIENTHOAI, QUYEN = @QUYEN, LUONGCOBAN = @LUONGCOBAN
	WHERE MANV = @MANV
END

--Sửa mật khẩu nhân viên
GO
CREATE PROC SP_NHANVIEN_SUA_MATKHAU
	@MANV NVARCHAR(10),
	@MATKHAU NVARCHAR(100)
AS
BEGIN
	UPDATE NHANVIEN SET MATKHAU = @MATKHAU
	WHERE MANV = @MANV
END

--Load Thông tin tài khoản
GO
CREATE PROC SP_NHANVIEN_LOADTAIKHOAN
	@MANV NVARCHAR(10)
AS
BEGIN
	SELECT *
	FROM NHANVIEN
	WHERE MANV = @MANV
END


--====>>>BÀN
--Load danh sách bàn
GO
CREATE PROC SP_TABLE_LOAD
AS
BEGIN
	SELECT *
	FROM BAN
END

--Thêm bàn
GO
CREATE PROC SP_TABLE_THEM
AS
BEGIN
	DECLARE @MA INT
	DECLARE @TEN NVARCHAR(10)
	SELECT  @MA = MAX(MABAN)
	FROM BAN
	SET @MA = @MA + 1
	SET @TEN = N'BÀN ' + CAST(@MA AS nvarchar(5))
	INSERT INTO BAN(MABAN, TENBAN)
	VALUES(@MA, @TEN)
END

EXEC SP_TABLE_THEM
--Xóa bàn
GO
CREATE PROC SP_TABLE_XOA
AS
BEGIN
	DECLARE @MA INT
	SELECT  @MA = MAX(MABAN)
	FROM BAN
	DELETE FROM BAN WHERE MABAN = @MA AND TRANGTHAI <> N'CÓ'
END

--====>>>SẢN PHẨM
--Load danh sách sản phẩm
GO
CREATE PROC SP_SANPHAM_LOAD
AS
BEGIN
	SELECT *
	FROM SANPHAM
END

--Kiểm tra tên sản phẩm có tồn tại hay không
GO
CREATE PROC SP_SANPHAM_KTRATENSP
	@TENSP NVARCHAR(100)
AS
BEGIN
	SELECT *
	FROM SANPHAM
	WHERE TENSP = @TENSP
END

--====>>>HÓA ĐƠN
--Load danh sách hóa đơn
GO
CREATE PROC SP_HOADON_DS
AS
BEGIN
	SELECT *
	FROM HOADON
	WHERE GHICHU <> N'CHƯA THANH TOÁN'
END


--Tìm hóa đơn theo ngày
GO
CREATE PROC SP_HOADON_TIM
	@TUNGAY DATE,
	@DENNGAY DATE
AS
BEGIN
	SELECT *
	FROM HOADON
	WHERE GHICHU <> N'CHƯA THANH TOÁN' AND CAST(NGAYXUAT AS DATE) >= @TUNGAY AND CAST(NGAYXUAT AS DATE) <= @DENNGAY
END


--Xem hóa đơn chi tiết
GO
CREATE PROC SP_HOADONCHITIET_DS
	@MAHOADON NVARCHAR(20)
AS
BEGIN
	SELECT *
	FROM HOADON HD JOIN HOADONCHITIET HDCT ON HD.MAHOADON = HDCT.MAHOADON JOIN SANPHAM SP ON SP.MASP = HDCT.MASP JOIN NHANVIEN NV ON NV.MANV = HD.MANV JOIN BAN B ON B.MABAN = HD.MABAN
	WHERE HD.MAHOADON = @MAHOADON
END

--Load hóa đơn thanh toán
GO
CREATE PROC SP_HOADONTHANHTOAN_LOAD
	@MABAN VARCHAR(10)
AS
BEGIN
	SELECT SP.TENSP, HDCT.SOLUONG, SP.DONGIABAN, (SP.DONGIABAN * HDCT.SOLUONG) THANHTIEN, HD.NGAYNHAP, NV.TENNV, HD.GIAMGIA, HD.VAT, HD.GHICHU
	FROM HOADON HD JOIN HOADONCHITIET HDCT ON HD.MAHOADON = HDCT.MAHOADON JOIN BAN B ON HD.MABAN = B.MABAN JOIN SANPHAM SP ON SP.MASP = HDCT.MASP JOIN NHANVIEN NV ON NV.MANV = HD.MANV
	WHERE (B.MABAN = @MABAN AND HD.GHICHU <> N'ĐÃ THU')
END
--Load doanh thu
GO
CREATE PROC SP_DOANHTHU_DS
AS
BEGIN
	SELECT SP.MASP, SP.TENSP, SP.DONGIABAN, SUM(CT.SOLUONG) SOLUONG, SUM(CT.SOLUONG*SP.DONGIABAN) THANHTIEN
	FROM HOADON HD JOIN HOADONCHITIET CT ON HD.MAHOADON = CT.MAHOADON JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE HD.GHICHU = N'ĐÃ THU'
	GROUP BY SP.MASP, SP.TENSP, SP.DONGIABAN
END

--Tìm doanh thu
GO
CREATE PROC SP_DOANHTHU_TIM
	@TUNGAY DATE,
	@DENNGAY DATE
AS
BEGIN
	SELECT SP.MASP, SP.TENSP, SP.DONGIABAN, SUM(CT.SOLUONG) SOLUONG, SUM(CT.SOLUONG*SP.DONGIABAN) THANHTIEN
	FROM HOADON HD JOIN HOADONCHITIET CT ON HD.MAHOADON = CT.MAHOADON JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE HD.GHICHU = N'ĐÃ THU' AND CAST(HD.NGAYXUAT AS DATE) >= @TUNGAY AND CAST(HD.NGAYXUAT AS DATE) <= @DENNGAY
	GROUP BY SP.MASP, SP.TENSP, SP.DONGIABAN
END

--THÊM MÓN
GO
CREATE PROC SP_HOADON_TONTAIHD
	@MABAN VARCHAR(5)
AS
BEGIN
	SELECT *
	FROM HOADON
	WHERE MABAN = @MABAN AND GHICHU <> N'ĐÃ THU'
END


--THANH TOÁN
GO
CREATE PROC SP_THANHTOANHOADON
	@MAHOADON VARCHAR(20),
	@THANHTOAN MONEY
AS
BEGIN
	UPDATE HOADON SET NGAYXUAT = GETDATE(), THANHTOAN = @THANHTOAN, GHICHU = N'ĐÃ THU'
	WHERE MAHOADON = @MAHOADON
END


GO
CREATE PROC SP_THEMHOADON
	@mahoadon varchar(20),
	@manv varchar(10),
	@maban varchar(10), 
	@giamgia float,
	@vat float
AS
BEGIN
	INSERT INTO HOADON(MAHOADON, NGAYNHAP, MANV, MABAN, GIAMGIA, VAT, GHICHU)	
	VALUES(@mahoadon, GETDATE(), @manv, @maban, @giamgia, @vat, N'CHƯA THANH TOÁN')
END

GO
CREATE PROC SP_THEMHOADONCHITIET
@mahoadon varchar(20), @masp varchar(10), @soluong int
AS
BEGIN
	DECLARE @KTRA INT
	DECLARE @SOSP INT = 1
	SELECT @KTRA = COUNT(*),  @SOSP = SOLUONG
	FROM HOADONCHITIET
	WHERE @mahoadon = MAHOADON AND @masp = MASP
	GROUP BY MAHOADON, SOLUONG

	IF (@KTRA>0)
	BEGIN
		IF(@soluong>0)
			UPDATE HOADONCHITIET SET SOLUONG = @soluong WHERE @mahoadon = MAHOADON AND @masp = MASP
		IF(@soluong=0)
			DELETE HOADONCHITIET WHERE @mahoadon = MAHOADON AND @masp = MASP
	END

	ELSE
	BEGIN
		IF (@soluong>0)
		BEGIN
			INSERT HOADONCHITIET(MAHOADON, MASP, SOLUONG)
			VALUES(@mahoadon, @masp, @soluong)
		END
	END
END


GO
CREATE TRIGGER TG_CapNhatHoaDonChiTiet
ON HOADONCHITIET FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @mahd NVARCHAR(20)
	
	SELECT @mahd = MAHOADON FROM Inserted
	
	DECLARE @maban NVARCHAR(10)
	
	SELECT @maban = MABAN FROM HOADON WHERE MAHOADON = @mahd AND GHICHU = N'CHƯA THANH TOÁN'

	DECLARE @count INT
	SELECT @count = COUNT(*) FROM HOADONCHITIET WHERE MAHOADON = @mahd

	IF (@count > 0)
	BEGIN
		UPDATE BAN SET TRANGTHAI = N'CÓ' WHERE MABAN = @maban
	END
	ELSE
	BEGIN
		UPDATE BAN SET TRANGTHAI = N'TRỐNG' WHERE MABAN = @maban
	END
END

GO
CREATE TRIGGER TG_CAPNHATHOADON
ON HOADON FOR UPDATE
AS
BEGIN
	DECLARE @mahd NVARCHAR(20)
	
	SELECT @mahd = MAHOADON FROM Inserted	
	
	DECLARE @maban NVARCHAR(10)
	
	SELECT @maban = MABAN FROM HOADON WHERE MAHOADON = @mahd
	
	DECLARE @count int = 0
	
	SELECT @count = COUNT(*) FROM HOADON WHERE MABAN = @maban AND GHICHU = N'CHƯA THANH TOÁN'
	
	IF (@count = 0)
		UPDATE BAN SET TRANGTHAI = N'TRỐNG' WHERE MABAN = @maban
END

--Chuyển bàn
GO
CREATE PROC ChuyenBan
@idTable1 NVARCHAR(10), @idTable2 NVARCHAR(10), @mahoadon varchar(20), @manv varchar(10)
AS BEGIN

	DECLARE @idFirstBill NVARCHAR(20)
	DECLARE @idSeconrdBill NVARCHAR(20)
	
	DECLARE @isFirstTablEmty INT = 1
	DECLARE @isSecondTablEmty INT = 1
	
	
	SELECT @idSeconrdBill = MAHOADON FROM HOADON WHERE MABAN = @idTable2 AND GHICHU = N'CHƯA THANH TOÁN'
	SELECT @idFirstBill = MAHOADON FROM HOADON WHERE MABAN = @idTable1 AND GHICHU = N'CHƯA THANH TOÁN'
	IF (@idFirstBill IS NULL AND @idSeconrdBill IS NULL)
		BEGIN
			RETURN
		END
	ELSE
	BEGIN
		IF (@idFirstBill IS NULL)
		BEGIN
			INSERT INTO HOADON(MAHOADON, NGAYNHAP, MANV, MABAN, GHICHU)
			VALUES(@mahoadon, GETDATE(), @manv, @idTable1, N'CHƯA THANH TOÁN')
		        
			SELECT @idFirstBill = MAX(MAHOADON) FROM HOADON WHERE MABAN = @idTable1 AND GHICHU = N'CHƯA THANH TOÁN'
		END
	
		SELECT @isFirstTablEmty = COUNT(*) FROM HOADONCHITIET WHERE MAHOADON = @idFirstBill

		IF (@idSeconrdBill IS NULL)
		BEGIN
			INSERT INTO HOADON(MAHOADON, NGAYNHAP, MANV, MABAN, GHICHU)
			VALUES(@mahoadon, GETDATE(), @manv, @idTable2, N'CHƯA THANH TOÁN')

			SELECT @idSeconrdBill = MAX(MAHOADON) FROM HOADON WHERE MABAN = @idTable2 AND GHICHU = N'CHƯA THANH TOÁN'
		
		END
	
		SELECT @isSecondTablEmty = COUNT(*) FROM HOADONCHITIET WHERE MAHOADON = @idSeconrdBill

		SELECT MAHOADON, MASP INTO IDBillInfoTable FROM HOADONCHITIET WHERE MAHOADON = @idSeconrdBill
	

		DECLARE @DEM INT = 0
		SELECT @DEM = COUNT(*) FROM HOADONCHITIET WHERE MAHOADON IN (SELECT MAHOADON FROM IDBillInfoTable) AND MASP IN (SELECT MASP FROM IDBillInfoTable)
		IF (@DEM > 0)
		BEGIN
			INSERT INTO HOADON(MAHOADON, NGAYNHAP, MANV, MABAN, GHICHU)
			VALUES(@mahoadon, GETDATE(), @manv, @idTable2, N'CHƯA THANH TOÁN')

			UPDATE HOADONCHITIET SET MAHOADON = @mahoadon WHERE MAHOADON = @idFirstBill
			UPDATE HOADONCHITIET SET MAHOADON = @idFirstBill WHERE MAHOADON IN (SELECT MAHOADON FROM IDBillInfoTable) AND MASP IN (SELECT MASP FROM IDBillInfoTable)
			UPDATE HOADONCHITIET SET MAHOADON = @idSeconrdBill WHERE MAHOADON = @mahoadon

			DELETE FROM HOADONCHITIET WHERE MAHOADON = @mahoadon
			DELETE FROM HOADON WHERE MAHOADON = @mahoadon
		END
		ELSE
		BEGIN
			UPDATE HOADONCHITIET SET MAHOADON = @idSeconrdBill WHERE MAHOADON = @idFirstBill
			print '-------'
			UPDATE HOADONCHITIET SET MAHOADON = @idFirstBill WHERE MAHOADON IN (SELECT MAHOADON FROM IDBillInfoTable) AND MASP IN (SELECT MASP FROM IDBillInfoTable)
		END
		DROP TABLE IDBillInfoTable
	
		IF (@isFirstTablEmty = 0)
		BEGIN
			UPDATE BAN SET TRANGTHAI = N'TRỐNG' WHERE MABAN = @idTable2
			DELETE FROM HOADON WHERE MABAN = @idTable2 AND GHICHU = N'CHƯA THANH TOÁN'
		END
			
		IF (@isSecondTablEmty= 0)
		BEGIN
			UPDATE BAN SET TRANGTHAI = N'TRỐNG' WHERE MABAN = @idTable1
			DELETE FROM HOADON WHERE MABAN = @idTable1 AND GHICHU = N'CHƯA THANH TOÁN'
		END
			
	END
END